apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: quick-note-secrets
  namespace: quick-note
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore

  target:
    name: quick-note-secret

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL