apiVersion: v1
kind: Secret

metadata:
  name: quick-note-secret
  namespace: quick-note

type: Opaque

data:
  NODE_ENV: "cHJvZHVjdGlvbg=="
  NEXT_PUBLIC_BASE_APP_URL: "aHR0cHM6Ly9xdWlja25vdGUuYXV0b3doYXQuYXBw"

  BETTER_AUTH_SECRET: "NEpiQjhjTkRuNEhOOTRlemg2TzlaVkZtSkNzcmczSFM="
  BETTER_AUTH_URL: "aHR0cHM6Ly9xdWlja25vdGUuYXV0b3doYXQuYXBw"