apiVersion: v1
kind: Secret

metadata:
  name: quick-note-secret
  namespace: quick-note

type: Opaque

data:
  NODE_ENV: "cHJvZHVjdGlvbg=="
  NEXT_PUBLIC_BASE_APP_URL: "aHR0cHM6Ly9xdWlja25vdGUuYXV0b3doYXQuYXBw"

  BETTER_AUTH_SECRET: "NEpiQjhjTkRuNEhOOTRlemg2TzlaVkZtSkNzcmczSFM="
  BETTER_AUTH_URL: "aHR0cHM6Ly9xdWlja25vdGUuYXV0b3doYXQuYXBw"

  R2_ENDPOINT: "aHR0cHM6Ly85M2IxZTI0M2VhM2FjMDUxODJjYzhjZjNkMmE3MTkxMS5yMi5jbG91ZGZsYXJlc3RvcmFnZS5jb20="
  R2_ACCESS_KEY_ID: "NzhhMmEzZjc2OThiNDdiMzVkYmJlZTFkMmVhMjBmZDQ="
  R2_SECRET_ACCESS_KEY: "ZmUwNDE3MWExZjc2YTgwMGIwYjRmZWRhMmZmZmY2NzMzY2QzYmIzMmQ0ZmQzNzg3YTJjYzYwNzFiYmYxZGVkYw=="
  R2_BUCKET_NAME: "cXVpY2stbm90ZQ=="