apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: gcp-secret-store
  namespace: quick-note
  
spec:
  provider:
    gcpsm:
      projectID: quck-note
      auth:
        workloadIdentity:
          clusterLocation: asia-south1
          clusterName: quick-note
          serviceAccountRef:
            name: quick-note-sa