import {
  ArchiveIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowSquareOutIcon,
  ArrowsDownUpIcon,
  ArticleIcon,
  BellIcon,
  CaretDownIcon,
  CheckIcon,
  CheckSquareIcon,
  CircleNotchIcon,
  CopyIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  FileIcon,
  FilePdfIcon,
  FileTextIcon,
  FunnelIcon,
  GlobeIcon,
  IdentificationCardIcon,
  ImageIcon,
  InfoIcon,
  KeyIcon,
  LinkIcon,
  LockIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  NotebookIcon,
  PaletteIcon,
  PlusIcon,
  PrinterIcon,
  SignOutIcon,
  SunIcon,
  TagIcon,
  TextTIcon,
  TicketIcon,
  Trash,
  UserIcon,
  UserPlusIcon,
  WarningIcon,
} from "@phosphor-icons/react";

export const Icons = {
  logo: NotebookIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowSquareOut: ArrowSquareOutIcon,
  archive: ArchiveIcon,
  arrowsDownUp: ArrowsDownUpIcon,
  article: ArticleIcon,
  bell: BellIcon,
  caretDown: CaretDownIcon,
  check: CheckIcon,
  checkSquare: CheckSquareIcon,
  copy: CopyIcon,
  dotsThree: DotsThreeIcon,
  dotsThreeVertical: DotsThreeVerticalIcon,
  download: DownloadSimpleIcon,
  email: EnvelopeIcon,
  file: FileIcon,
  fileText: FileTextIcon,
  funnel: FunnelIcon,
  globe: GlobeIcon,
  image: ImageIcon,
  link: LinkIcon,
  password: LockIcon,
  user: UserIcon,
  userPlus: UserPlusIcon,
  palette: PaletteIcon,
  idCard: IdentificationCardIcon,
  notebook: NotebookIcon,
  plus: PlusIcon,
  signOut: SignOutIcon,
  magnifyingGlass: MagnifyingGlassIcon,
  sun: SunIcon,
  moon: MoonIcon,
  loader2: CircleNotchIcon,
  tag: TagIcon,
  textT: TextTIcon,
  ticket: TicketIcon,
  trash: Trash,
  printer: PrinterIcon,
  warning: WarningIcon,
  filePdf: FilePdfIcon,
  lock: LockIcon,
  info: InfoIcon,
  lockOpen: LockOpenIcon,
  key: KeyIcon
};
