import {
  ArchiveIcon,
  ArrowRightIcon,
  BellIcon,
  CheckIcon,
  CheckSquareIcon,
  CopyIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  EnvelopeIcon,
  IdentificationCardIcon,
  ImageIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  NotebookIcon,
  PaletteIcon,
  PlusIcon,
  SignOutIcon,
  SunIcon,
  TagIcon,
  UserIcon,
  UserPlusIcon,
  CircleNotchIcon,
} from "@phosphor-icons/react";

export const Icons = {
  logo: NotebookIcon,
  arrowRight: ArrowRightIcon,
  archive: ArchiveIcon,
  bell: BellIcon,
  check: CheckIcon,
  checkSquare: CheckSquareIcon,
  copy: CopyIcon,
  dotsThree: DotsThreeIcon,
  dotsThreeVertical: DotsThreeVerticalIcon,
  email: EnvelopeIcon,
  image: ImageIcon,
  password: LockIcon,
  user: UserIcon,
  userPlus: UserPlusIcon,
  palette: PaletteIcon,
  idCard: IdentificationCardIcon,
  notebook: NotebookIcon,
  plus: PlusIcon,
  signOut: SignOutIcon,
  magnifyingGlass: MagnifyingGlassIcon,
  sun: SunIcon,
  moon: MoonIcon,
  loader2: CircleNotchIcon,
  tag: TagIcon,
};
