name: Test GCP Auth

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/quick-note/quick-note:${{ github.sha }} \
            .

      - name: Push Docker Image
        run: |
          docker push \
            asia-south1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/quick-note/quick-note:${{ github.sha }}

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials quick-note \
            --zone asia-south1 \
            --project quck-note

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/
          